ARG BASE_IMAGE=openanolis/anolisos:23.4
FROM $BASE_IMAGE AS builder

ARG NODE_BRANCH=v26.3.1

WORKDIR /home

RUN dnf install -y unzip g++
RUN curl -LO https://github.com/nodejs/node/archive/refs/tags/${NODE_BRANCH}.zip \
  && unzip ${NODE_BRANCH}.zip \
  && folder=node-${NODE_BRANCH#v} \
  && echo "folder=$folder" \
  && cd $folder \
  && ./configure --openssl-no-asm \
  && make -j$(nproc) prefix=/usr/local \
  && make -j$(nproc) install DESTDIR=/tmp/node-staging prefix=/usr/local \
  && find /tmp/node-staging \
  && /tmp/node-staging/usr/local/bin/node --version

FROM $BASE_IMAGE

ARG NODE_BRANCH=v26.3.1

COPY --from=builder /tmp/node-staging/usr/local /usr/local

LABEL maintainer="徐晓伟 <xuxiaowei@xuxiaowei.com.cn>" \
      license="Apache-2.0" \
      org.opencontainers.image.authors="徐晓伟 <xuxiaowei@xuxiaowei.com.cn>" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.title="LoongArch node" \
      org.opencontainers.image.description="node ${NODE_BRANCH} for LoongArch (loong64)" \
      org.opencontainers.image.version="${NODE_BRANCH}" \
      org.opencontainers.image.url="https://github.com/kubernetes-loong64/node-loong64" \
      org.opencontainers.image.source="https://github.com/kubernetes-loong64/node-loong64"

RUN dnf install -y libatomic \
    && dnf clean all \
    && rm -rf /var/cache/dnf \
    && node -v
