ARG BASE_IMAGE=openanolis/anolisos:23.4
FROM $BASE_IMAGE AS builder

ARG NODE_VERSION=v22.23.1

WORKDIR /home

RUN dnf install -y curl tar
RUN curl -fsSL https://unofficial-builds.nodejs.org/download/release/${NODE_VERSION}/node-${NODE_VERSION}-linux-loong64.tar.gz \
  -o node.tar.gz \
  && mkdir -p /tmp/node-staging/usr/local \
  && tar -xzf node.tar.gz -C /tmp/node-staging/usr/local --strip-components=1 \
  && /tmp/node-staging/usr/local/bin/node --version

FROM $BASE_IMAGE

ARG NODE_VERSION=v22.23.1

COPY --from=builder /tmp/node-staging/usr/local /usr/local

LABEL maintainer="徐晓伟 <xuxiaowei@xuxiaowei.com.cn>" \
      license="Apache-2.0" \
      org.opencontainers.image.authors="徐晓伟 <xuxiaowei@xuxiaowei.com.cn>" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.title="LoongArch node" \
      org.opencontainers.image.description="node ${NODE_VERSION} for LoongArch (loong64)" \
      org.opencontainers.image.version="${NODE_VERSION}" \
      org.opencontainers.image.url="https://github.com/kubernetes-loong64/node-loong64" \
      org.opencontainers.image.source="https://github.com/kubernetes-loong64/node-loong64"

RUN node -v \
    && npm -v \
    && npx -v
